import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>James Kwok | Developer & Designer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  );
}
