import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Main from '@/components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>James | Developer & Designer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Main />
    </div>
  );
}
